metrics_enabled : true
debug : false
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - org.skife
    - xx-responses
    - com.hello

common_db:
  driverClass: org.postgresql.Driver
  user: common
  password: hello-common
  url: jdbc:postgresql://common.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/common
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  initialSize: 8

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 5555
      idleTimeout: 25 seconds
  adminConnectors:
    - type: http
      port: 5556
      idleTimeout: 25 seconds
  requestLog:
    timeZone: UTC
    appenders:
      - type: file
        currentLogFilename: /var/log/suripu-service/suripu-service-access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /var/log/suripu-service/suripu-service-access-%d{yyyy-MM-dd}.log.gz
        archivedFileCount: 7
      - type: papertrail
        host: logs2.papertrailapp.com
        port: 11366
        ident: suripu-service-prod

logging:
  level: INFO
  loggers:
    com.hello.suripu: INFO
    com.amazonaws: WARN
  appenders:
    - type: file
      threshold: INFO
      currentLogFilename: /var/log/suripu-service/suripu-service.log
      archivedLogFilenamePattern: /var/log/suripu-service/suripu-service-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: suripu-service-prod
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    audio_features : audio_features
    activity_stream : activity_stream
    registrations: registrations
    encode_audio: encode_audio
    batch_pill_data : batch_pill_data
    sense_sensors_data : sense_sensors_data
    logs: logs


audio_bucket_name : hello-data

sense_upload_configuration:
  non_peak_hour_lower_bound: 9
  non_peak_hour_upper_bound: 20
  week_days_only: false
  increased_non_peak_interval: 7
  increased_peak_interval: 5
  default_interval: 1
  
ota_configuration:
  start_update_window_hour: 11
  end_update_window_hour: 20
  device_uptime_delay: 60
  always_ota_groups: [chris-dev, video-photoshoot, victor]
  s3cache_expire_minutes: 20

kinesis_logger:
  stream_name: logs
  enabled : true
  buffer_size: 100
  origin: suripu-service

aws_metric_namespace: suripu-service
dynamo_client_configuration:
  max_connections: 100
  connection_timeout: 100
  connection_max_idle_millis: 60000
  max_error_retry: 1
  request_timeout: 200

kinesis_client_configuration:
  max_connections: 100
  connection_timeout: 200
  connection_max_idle_millis: 60000
  max_error_retry: 1
  request_timeout: 200

aws_access_key_s3: AKIAJVQV7XJU23UWILSQ
aws_access_secret_s3: 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

ring_duration_sec: 240


dynamodb:
  region: us-east-1
  tables:
    alarm_info : prod_alarm_info
    calibration: prod_calibration
    features : features
    file_manifest: prod_file_manifest
    firmware_upgrade_path : prod_fw_upgrade_path
    firmware_versions : prod_firmware_versions_mapping
    ota_history : ota_history
    ota_file_settings: prod_ota_file_settings
    pill_key_store : pill_key_store
    ring_time_history: prod_ring_history_by_account
    sense_key_store : key_store
    sense_state: prod_sense_state
    swap_intents: prod_swap_intents
    sync_response_commands : prod_response_commands
    teams : teams


  endpoints:
      alarm_info : http://dynamodb.us-east-1.amazonaws.com
      calibration : http://dynamodb.us-east-1.amazonaws.com
      features : http://dynamodb.us-east-1.amazonaws.com
      file_manifest: http://dynamodb.us-east-1.amazonaws.com
      firmware_upgrade_path : http://dynamodb.us-east-1.amazonaws.com
      firmware_versions : http://dynamodb.us-east-1.amazonaws.com
      ota_history : http://dynamodb.us-east-1.amazonaws.com
      ota_file_settings: http://dynamodb.us-east-1.amazonaws.com
      pill_key_store : http://dynamodb.us-east-1.amazonaws.com
      ring_time_history: http://dynamodb.us-east-1.amazonaws.com
      sense_key_store : http://dynamodb.us-east-1.amazonaws.com
      sense_state: http://dynamodb.us-east-1.amazonaws.com
      swap_intents: http://dynamodb.us-east-1.amazonaws.com
      sync_response_commands : http://dynamodb.us-east-1.amazonaws.com
      teams : http://dynamodb.us-east-1.amazonaws.com
